In [13]:
# dependencies

from Bio import AlignIO
from Bio import SeqIO
import re
import pandas as pd

In [14]:
# Converting BioCatNet fasta file to dataframe that includes the sequence and the family name

def biocatnet_fasta_to_df(input_fasta):
    data = {'accession': [], 'SFID': [], 'GI': [], 'taxonID': [], 'sequence': []}
    with open(input_fasta) as fp:
        for record in SeqIO.parse(fp, 'fasta'):
            accession = record.id
            sfid = re.findall(r"sfid\|(\d+)", record.id)
            gi = re.findall(r"gi\|(\d+)", record.id)
            taxonID = re.findall(r"taxonID\|(\d+)", record.id)
            sequence = str(record.seq)

            #Attach to dict.
            data['accession'].append(accession)
            data['SFID'].append(", ".join(sfid))
            data['GI'].append(", ".join(gi))
            data['taxonID'].append(", ".join(taxonID))
            data['sequence'].append(sequence)
    df = pd.DataFrame(data)
    return df

In [15]:
biocatnet_r1 = biocatnet_fasta_to_df('/home/alecia/chapter3-repo/output/hmm_search_1/biocatnet/5/ihelixhits_e_0p00001_z__T_.fasta')
biocatnet_r2 = biocatnet_fasta_to_df('/home/alecia/chapter3-repo/output/hmm_search_2/biocatnet/5/ihelixhits_e_0p00001_z__T_.fasta')

In [16]:
biocatnet_r1

,accession,SFID,GI,taxonID,sequence
0,sid|107075|pid|82008|hfid|211|sfid|6|gb|ERL945...,6,546684943,77166,-EDIMAQCFVFFFAGFETSST--TMTFALLELAQH
1,sid|107075|pid|82008|hfid|211|sfid|6|gb|ERL945...,6,546684943,77166,-SDIIAQCFVFFIAGFETSSS--TMTFTMLELAQH
2,sid|107075|pid|82008|hfid|211|sfid|6|gb|ERL945...,6,546684943,77166,-SDIIAQCFVFFIAGFETSSS--TMTFTMLELAQH
3,sid|107075|pid|82008|hfid|211|sfid|6|gb|ERL945...,6,546684943,77166,-NDIIGQCFVFFIAGFETSSS--TMTFTMLELAQN
4,sid|85794|pid|63405|hfid|120|sfid|4|gi|3544699...,4,"354469982, 537224038",10029,DKDLRAEVDTFMFEGHDTTAS--GISWIFYALATH
...,...,...,...,...,...
16788,sid|10755|pid|7643|hfid|31|sfid|2|gi|589922350...,2,589922350,230844,--------LDLFLAGTETTST--TLRWALLYMA--
16789,sid|77202|pid|56248|hfid|214|sfid|6|gi|1947440...,6,194744078,7217,-EAITAQAFIFYIAGQETTGS--TAAFTIYELAQ-
16790,sid|10932|pid|7797|hfid|34|sfid|2|gb|AAO49472....,2,28629124,7955,--NFLTTINNLFGAGIDTTVT--TLRWGLLLIAKY
16791,sid|10933|pid|7797|hfid|34|sfid|2|gi|41053875|...,2,41053875,7955,--NFLTTINNLFGAGIDTTVT--TLRWGLLLIAKY
16792,sid|10965|pid|7825|hfid|34|sfid|2|gb|AAH65455....,2,41223383,7955,--NFLTTINNLFGAGIDTTVT--TLRWGLLLIAKY

In [17]:
biocatnet_r2

,accession,SFID,GI,taxonID,sequence
0,sid|107075|pid|82008|hfid|211|sfid|6|gb|ERL945...,6,546684943,77166,ITEEDI-MAQCFVFFFA------GFETSST--TMTFALLELAQH-
1,sid|107075|pid|82008|hfid|211|sfid|6|gb|ERL945...,6,546684943,77166,ISESDI-IAQCFVFFIA------GFETSSS--TMTFTMLELAQH-
2,sid|107075|pid|82008|hfid|211|sfid|6|gb|ERL945...,6,546684943,77166,ISESDI-IAQCFVFFIA------GFETSSS--TMTFTMLELAQH-
3,sid|107075|pid|82008|hfid|211|sfid|6|gb|ERL945...,6,546684943,77166,LSENDI-IGQCFVFFIA------GFETSSS--TMTFTMLELAQN-
4,sid|85794|pid|63405|hfid|120|sfid|4|gi|3544699...,4,"354469982, 537224038",10029,LSDKDL-RAEVDTFMFE------GHDTTAS--GISWIFYALATHP
...,...,...,...,...,...
27819,sid|8892|pid|6197|hfid|17|sfid|2|gi|488589356|...,2,"488589356, 488589360",9361,-----L-ILTGLSLFFA------GTETTST--TLRYGFLLMLKYP
27820,sid|4148|pid|2700|hfid|1066|sfid|150|gi|515044...,150,515044448,1829,----DL-VRLATFLFGA------GQDTTAR--LITAAFRLIAENP
27821,sid|79738|pid|58328|hfid|1592|sfid|706|gb|EYU2...,706,604301429,4155,----QI-KAILVDIVAG------GSDTTAT--MVEWVMTELLHNP
27822,sid|21392|pid|16201|hfid|653|sfid|82|gi|568865...,82,568865636,2711,-----I-KAICVTLIVA------AADTSVV--TLTWAIALLVNN-
27823,sid|21393|pid|16201|hfid|653|sfid|82|gi|567886...,82,567886762,85681,-----I-KAICVTLIVA------AADTSVV--TLTWAIALLVNN-

In [18]:
r1r2_merged_biocatnet = (pd.merge(biocatnet_r1, biocatnet_r2, how='outer', on=['GI', 'taxonID'])
                    .fillna(0))
r1r2_merged_biocatnet

,accession_x,SFID_x,GI,taxonID,sequence_x,accession_y,SFID_y,sequence_y
0,0,0,,,0,sid|110304|pid|33711|hfid|829|sfid|107/226-261,107,LTEQEL-LDHCIGLLIA------GHETTAS--QIPSFVYALLDQP
1,sid|29166|pid|21798|hfid|445|sfid|55|gi|101208...,55,"10120838, 117179, 18158928, 7546424, 18158929",5507,-SDAVQIAFLLLVAGNATMVN--MIALGVATLAQH,0,0,0
2,sid|29169|pid|21798|hfid|445|sfid|55|gi|101208...,55,"10120840, 7767229",5507,-SDAVQIAFLLLVAGNATMVN--MIALGVATLAQH,0,0,0
3,0,0,10140663,39947,0,sid|41672|pid|29559|hfid|692|sfid|89|gb|AAG134...,89,LTDDEL-VMLCSEFLVA------GTDSTSA--ALQWIMAELVRNP
4,sid|41627|pid|29515|hfid|692|sfid|89|gb|AAG135...,89,10140665,39947,DDEMVSLCSEFLSAGTDTTAT--ALQWIMAELVKN,sid|41627|pid|29515|hfid|692|sfid|89|gb|AAG135...,89,LTDDEM-VSLCSEFLSA------GTDTTAT--ALQWIMAELVKNP
...,...,...,...,...,...,...,...,...
30430,sid|6786|pid|4645|hfid|1|sfid|1|gb|ABD74631.1|...,1,98990276,94951,DEKIVGIVNDLFGAGFDTIST--ALSWSVMYLVA-,sid|6786|pid|4645|hfid|1|sfid|1|gb|ABD74631.1|...,1,MSDEKI-VGIVNDLFGA------GFDTIST--ALSWSVMYLVAYP
30431,sid|9714|pid|6817|hfid|18|sfid|2|gi|98991773|g...,2,"98991773, 311893309",9606,-ENLVGTVADLFVAGTETTST--TLRYGLLLLLKH,sid|9714|pid|6817|hfid|18|sfid|2|gi|98991773|g...,2,-NIENL-VGTVADLFVA------GTETTST--TLRYGLLLLLKHP
30432,sid|35249|pid|25430|hfid|375|sfid|51|gi|990289...,51,99028936,7955,DDEIAGMLIGLLLAGQHTSST--TSAWMGFFLAR-,sid|35249|pid|25430|hfid|375|sfid|51|gi|990289...,51,LSDDEI-AGMLIGLLLA------GQHTSST--TSAWMGFFLAR--
30433,sid|6775|pid|4635|hfid|1|sfid|1|gb|ABF60890.1|...,1,99029236,7957,DEKIVGIVNDLFGAGFDTIST--ALSWGVVYLVA-,sid|6775|pid|4635|hfid|1|sfid|1|gb|ABF60890.1|...,1,-SDEKI-VGIVNDLFGA------GFDTIST--ALSWGVVYLVAYP
30434,0,0,9957087,3888,0,sid|58223|pid|41225|hfid|653|sfid|82|gb|AAG092...,82,-----I-KATTLELILG------GSDTTAG--TLTWAMCLLLKHP

In [25]:
column = r1r2_merged_biocatnet['sequence_x']
r1r2_merged_biocatnet['char_x'] = column.str[16]
r1r2_merged_biocatnet['char_x2'] = column.str[17]

r1r2_merged_biocatnet

,accession_x,SFID_x,GI,taxonID,sequence_x,accession_y,SFID_y,sequence_y,char,char_x,char_x2
0,0,0,,,0,sid|110304|pid|33711|hfid|829|sfid|107/226-261,107,LTEQEL-LDHCIGLLIA------GHETTAS--QIPSFVYALLDQP,E,NaN,NaN
1,sid|29166|pid|21798|hfid|445|sfid|55|gi|101208...,55,"10120838, 117179, 18158928, 7546424, 18158929",5507,-SDAVQIAFLLLVAGNATMVN--MIALGVATLAQH,0,0,0,NaN,A,T
2,sid|29169|pid|21798|hfid|445|sfid|55|gi|101208...,55,"10120840, 7767229",5507,-SDAVQIAFLLLVAGNATMVN--MIALGVATLAQH,0,0,0,NaN,A,T
3,0,0,10140663,39947,0,sid|41672|pid|29559|hfid|692|sfid|89|gb|AAG134...,89,LTDDEL-VMLCSEFLVA------GTDSTSA--ALQWIMAELVRNP,D,NaN,NaN
4,sid|41627|pid|29515|hfid|692|sfid|89|gb|AAG135...,89,10140665,39947,DDEMVSLCSEFLSAGTDTTAT--ALQWIMAELVKN,sid|41627|pid|29515|hfid|692|sfid|89|gb|AAG135...,89,LTDDEM-VSLCSEFLSA------GTDTTAT--ALQWIMAELVKNP,D,D,T
...,...,...,...,...,...,...,...,...,...,...,...
30430,sid|6786|pid|4645|hfid|1|sfid|1|gb|ABD74631.1|...,1,98990276,94951,DEKIVGIVNDLFGAGFDTIST--ALSWSVMYLVA-,sid|6786|pid|4645|hfid|1|sfid|1|gb|ABD74631.1|...,1,MSDEKI-VGIVNDLFGA------GFDTIST--ALSWSVMYLVAYP,D,D,T
30431,sid|9714|pid|6817|hfid|18|sfid|2|gi|98991773|g...,2,"98991773, 311893309",9606,-ENLVGTVADLFVAGTETTST--TLRYGLLLLLKH,sid|9714|pid|6817|hfid|18|sfid|2|gi|98991773|g...,2,-NIENL-VGTVADLFVA------GTETTST--TLRYGLLLLLKHP,E,E,T
30432,sid|35249|pid|25430|hfid|375|sfid|51|gi|990289...,51,99028936,7955,DDEIAGMLIGLLLAGQHTSST--TSAWMGFFLAR-,sid|35249|pid|25430|hfid|375|sfid|51|gi|990289...,51,LSDDEI-AGMLIGLLLA------GQHTSST--TSAWMGFFLAR--,H,H,T
30433,sid|6775|pid|4635|hfid|1|sfid|1|gb|ABF60890.1|...,1,99029236,7957,DEKIVGIVNDLFGAGFDTIST--ALSWGVVYLVA-,sid|6775|pid|4635|hfid|1|sfid|1|gb|ABF60890.1|...,1,-SDEKI-VGIVNDLFGA------GFDTIST--ALSWGVVYLVAYP,D,D,T
30434,0,0,9957087,3888,0,sid|58223|pid|41225|hfid|653|sfid|82|gb|AAG092...,82,-----I-KATTLELILG------GSDTTAG--TLTWAMCLLLKHP,D,NaN,NaN

In [35]:
# If sequence in I_Helix y, take the acid alcohol - if not, take the acid alcohol in I Helix x

result_data = []

for index, row in r1r2_merged_biocatnet.iterrows():
    if row['sequence_y'] != 0:
        acid = row['sequence_y'][25]
        alc = row['sequence_y'][26]
    else:
        acid = row['sequence_x'][16]
        alc = row['sequence_x'][17]

    # Append a dictionary with relevant information to the result_data list
    result_data.append({
        'taxon': row['taxonID'],
        'GI': row['GI'],
        'sequence_y': row['sequence_y'],
        'sequence_x': row['sequence_x'],
        'accession_x': row['accession_x'],
        'accession_y': row['accession_y'],
        'SFID_x': row['SFID_x'],
        'SFID_y': row['SFID_y'],
        'acid': acid,
        'alc': alc,
    })


# Create a DataFrame from the result_data list
result_df = pd.DataFrame(result_data)

In [36]:
result_df

,taxon,GI,sequence_y,sequence_x,accession_x,accession_y,SFID_x,SFID_y,acid,alc
0,,,LTEQEL-LDHCIGLLIA------GHETTAS--QIPSFVYALLDQP,0,0,sid|110304|pid|33711|hfid|829|sfid|107/226-261,0,107,E,T
1,5507,"10120838, 117179, 18158928, 7546424, 18158929",0,-SDAVQIAFLLLVAGNATMVN--MIALGVATLAQH,sid|29166|pid|21798|hfid|445|sfid|55|gi|101208...,0,55,0,A,T
2,5507,"10120840, 7767229",0,-SDAVQIAFLLLVAGNATMVN--MIALGVATLAQH,sid|29169|pid|21798|hfid|445|sfid|55|gi|101208...,0,55,0,A,T
3,39947,10140663,LTDDEL-VMLCSEFLVA------GTDSTSA--ALQWIMAELVRNP,0,0,sid|41672|pid|29559|hfid|692|sfid|89|gb|AAG134...,0,89,D,S
4,39947,10140665,LTDDEM-VSLCSEFLSA------GTDTTAT--ALQWIMAELVKNP,DDEMVSLCSEFLSAGTDTTAT--ALQWIMAELVKN,sid|41627|pid|29515|hfid|692|sfid|89|gb|AAG135...,sid|41627|pid|29515|hfid|692|sfid|89|gb|AAG135...,89,89,D,T
...,...,...,...,...,...,...,...,...,...,...
30430,94951,98990276,MSDEKI-VGIVNDLFGA------GFDTIST--ALSWSVMYLVAYP,DEKIVGIVNDLFGAGFDTIST--ALSWSVMYLVA-,sid|6786|pid|4645|hfid|1|sfid|1|gb|ABD74631.1|...,sid|6786|pid|4645|hfid|1|sfid|1|gb|ABD74631.1|...,1,1,D,T
30431,9606,"98991773, 311893309",-NIENL-VGTVADLFVA------GTETTST--TLRYGLLLLLKHP,-ENLVGTVADLFVAGTETTST--TLRYGLLLLLKH,sid|9714|pid|6817|hfid|18|sfid|2|gi|98991773|g...,sid|9714|pid|6817|hfid|18|sfid|2|gi|98991773|g...,2,2,E,T
30432,7955,99028936,LSDDEI-AGMLIGLLLA------GQHTSST--TSAWMGFFLAR--,DDEIAGMLIGLLLAGQHTSST--TSAWMGFFLAR-,sid|35249|pid|25430|hfid|375|sfid|51|gi|990289...,sid|35249|pid|25430|hfid|375|sfid|51|gi|990289...,51,51,H,T
30433,7957,99029236,-SDEKI-VGIVNDLFGA------GFDTIST--ALSWGVVYLVAYP,DEKIVGIVNDLFGAGFDTIST--ALSWGVVYLVA-,sid|6775|pid|4635|hfid|1|sfid|1|gb|ABF60890.1|...,sid|6775|pid|4635|hfid|1|sfid|1|gb|ABF60890.1|...,1,1,D,T
30434,3888,9957087,-----I-KATTLELILG------GSDTTAG--TLTWAMCLLLKHP,0,0,sid|58223|pid|41225|hfid|653|sfid|82|gb|AAG092...,0,82,D,T

In [34]:
acidalc = result_df.groupby('acid').alc.value_counts()
acidalc.to_csv('biocatnet_r1r2_allacidalc.csv')